<?php
/*-------------------------------------------------------*\
|  PHP BasicFramework - Ready to use PHP site framework   |
|  License: LGPL, see LICENSE                             |
\*-------------------------------------------------------*
|                       CONFIGURATION                     |
\*                                                       */

// Note : this file is generated by the configuration script. 
// Only edit section below --CONIG-OVERRIDE-BELOW

// Security check, do not remove this line
if (!defined("C_SECURITY")) die();

//--AUTOCONFIG-START

$_conf = array (
  'auto_detect_base_url' => true,
  'base_url' => '/',
  'db' => 
  array (
    'database' => 
    array (
      0 => 'pdo_sqlite3',
      1 => 'database.sqlite',
      2 => 'db',
      3 => '',
      4 => '',
    ),
  ),
  'encoding' => 'UTF-8',
  'error_debug' => true,
  'error_email' => '',
  'error_log' => true,
  'error_reporting' => 'E_ALL | E_STRICT',
  'error_send_mail' => false,
  'folder_admin' => 'core/admin/',
  'folder_cached' => 'core/data/cached_templates/',
  'folder_compiled' => 'core/data/compiled_templates/',
  'folder_compiled_forms' => 'core/data/compiled_forms/',
  'folder_css' => 'css/',
  'folder_data' => 'core/data/',
  'folder_db' => 'core/data/db/',
  'folder_forms' => 'core/forms/',
  'folder_framework' => 'core/lib/phpbf/',
  'folder_img' => 'img/',
  'folder_js' => 'js/',
  'folder_lib' => 'core/lib/',
  'folder_log' => 'core/data/log/',
  'folder_model' => 'core/model/',
  'folder_modules' => 'core/lib/phpbf/modules/',
  'folder_smarty' => 'core/lib/smarty/',
  'folder_tags' => 'core/tags/',
  'folder_tpl' => 'core/templates/',
  'folder_translations' => 'core/translations/',
  'general_file_to_load' => '',
  'locale_enabled' => true,
  'locale_get_param_name' => 'locale',
  'locale_languages' => 
  array (
    'en' => 
    array (
      0 => 'US',
      1 => 'UK',
    ),
  ),
  'locale_set_php' => true,
  'locale_url_syntax' => 'lang',
  'locale_use_cookie' => '1',
  'locale_use_get' => false,
  'locale_use_session' => false,
  'locale_use_url' => false,
  'locale_use_user' => false,
  'mail_default_to' => '@',
  'mail_method' => 'mail',
  'mail_sendmail_path' => '',
  'mail_smtp_host' => 'localhost',
  'mail_smtp_password' => '',
  'mail_smtp_port' => '',
  'mail_smtp_username' => '',
  'page_default' => 'example',
  'page_error' => 'error',
  'page_logged' => 'logged',
  'path_to_root' => './../../../',
  'project_id' => 'Example',
  'tables' => 
  array (
    'users' => '',
    'groups' => '',
    'users_groups' => '',
    'car' => 'car',
  ),
  'template_cache' => false,
  'template_cache_lifetime' => 86400,
  'template_compile_check' => true,
  'template_default_content_type' => 'text/html',
  'template_default_creator' => 'My name',
  'template_smarty_debug' => false,
  'time_default_zone' => 'GMT',
  'window_title' => 'My site - %s',
);
$_conf["error_reporting"] = E_ALL | E_STRICT;

//--AUTOCONFIG-END

//--CONIG-OVERRIDE-BELOW

?>